import { z } from 'zod';

export const generateFoodPlanSchema = z.object({
  echipament_gatit: z.array(z.string()).optional(),
  restrictii: z.array(z.string()).optional(),
  include_alimente: z.string().optional(),
  fara_aceste_alimente: z.string().optional(),
  // Obiectiv
  general_calorii: z.string().optional(),
  general_proteine: z.string().optional(),
  general_carbohidrati: z.string().optional(),
  general_grasimi: z.string().optional(),
  general_procent_mic_dejun: z.string().optional(),
  general_procent_pranz: z.string().optional(),
  general_procent_cina: z.string().optional(),
  general_procent_gustari: z.string().optional(),

  luni_calorii: z.string().optional(),
  luni_proteine: z.string().optional(),
  luni_carbohidrati: z.string().optional(),
  luni_grasimi: z.string().optional(),
  luni_procent_mic_dejun: z.string().optional(),
  luni_procent_pranz: z.string().optional(),
  luni_procent_cina: z.string().optional(),
  luni_procent_gustari: z.string().optional(),

  marti_calorii: z.string().optional(),
  marti_proteine: z.string().optional(),
  marti_carbohidrati: z.string().optional(),
  marti_grasimi: z.string().optional(),
  marti_procent_mic_dejun: z.string().optional(),
  marti_procent_pranz: z.string().optional(),
  marti_procent_cina: z.string().optional(),
  marti_procent_gustari: z.string().optional(),

  miercuri_calorii: z.string().optional(),
  miercuri_proteine: z.string().optional(),
  miercuri_carbohidrati: z.string().optional(),
  miercuri_grasimi: z.string().optional(),
  miercuri_procent_mic_dejun: z.string().optional(),
  miercuri_procent_pranz: z.string().optional(),
  miercuri_procent_cina: z.string().optional(),
  miercuri_procent_gustari: z.string().optional(),

  joi_calorii: z.string().optional(),
  joi_proteine: z.string().optional(),
  joi_carbohidrati: z.string().optional(),
  joi_grasimi: z.string().optional(),
  joi_procent_mic_dejun: z.string().optional(),
  joi_procent_pranz: z.string().optional(),
  joi_procent_cina: z.string().optional(),
  joi_procent_gustari: z.string().optional(),

  vineri_calorii: z.string().optional(),
  vineri_proteine: z.string().optional(),
  vineri_carbohidrati: z.string().optional(),
  vineri_grasimi: z.string().optional(),
  vineri_procent_mic_dejun: z.string().optional(),
  vineri_procent_pranz: z.string().optional(),
  vineri_procent_cina: z.string().optional(),
  vineri_procent_gustari: z.string().optional(),

  sambata_calorii: z.string().optional(),
  sambata_proteine: z.string().optional(),
  sambata_carbohidrati: z.string().optional(),
  sambata_grasimi: z.string().optional(),
  sambata_procent_mic_dejun: z.string().optional(),
  sambata_procent_pranz: z.string().optional(),
  sambata_procent_cina: z.string().optional(),
  sambata_procent_gustari: z.string().optional(),

  duminica_calorii: z.string().optional(),
  duminica_proteine: z.string().optional(),
  duminica_carbohidrati: z.string().optional(),
  duminica_grasimi: z.string().optional(),
  duminica_procent_mic_dejun: z.string().optional(),
  duminica_procent_pranz: z.string().optional(),
  duminica_procent_cina: z.string().optional(),
  duminica_procent_gustari: z.string().optional(),

  // Calculator
  sex: z.string().optional(),
  varsta: z.string().optional(),
  inaltime: z.string().optional(),
  greutate: z.string().optional(),
  nivel_activitate: z.string().optional(),
});

export type GenerateFoodPlanFormData = z.infer<typeof generateFoodPlanSchema>;
